### ISSUE TITLE
Does emacs+ do Lisp? Can I put macros in .emacs?

### ISSUE THREAD

**Issue by adam66** [MulgaSoft/e4macs#22]
Possibly sounds like a dumb question but I've been going through all the docs on eclipse marketplace, google groups and github but it's still not clear. I assume I can't use my own .emacs file, but could this be used as a feature request?

**Comment by mfeber** [comment]
Emacs+ is lispless.

**Comment by adam66** [comment]
That would too awesome!


-------- Original Message --------
*Subject: *Re: [MulgaSoft/e4macs] Does emacs+ do Lisp? Can I put macros in 
.emacs? (#22)
*From: *Mark Feber <notifications@github.com>
*To: *MulgaSoft/e4macs <e4macs@noreply.github.com>
*Cc: *adam66 <adam.hardy@cyberspaceroad.com>, Author <author@noreply.github.com>
*Date: *Sat Sep 17 2016 18:17:43 GMT+0100 (GMT Standard Time)
