### ISSUE TITLE
Problems Remapping Java Format and Save on Mac

### ISSUE THREAD

**Issue by marcel-becker** [MulgaSoft/e4macs#23]
Hi Mark, 

I this code still under active development/maintenance? 

I installed all 4 Emacs+ plugins in my Eclipse Oxygen disto, including the Mac Command and Optional Mac Command plugins. 
I tried to remap Format  to Command+Shift+F and Save to Command+S but neither of the commands would work.
I can use "Meta-x format" to format code, but I could not get Command+Shift-F to work. 
I remapped all instances of Format I could find in the preferences - Keys panel. 
When using the default key mapping, I get a Format command that applies to Java source code, but the command is not there when using Emacs+ keybindings. 

Similarly for the Save command. I can use Ctrl-x-s to save, but Command+S would not work. 

I also tried to map Command+3  back to Quick Access but that did not work either. 

Without the mac command key plugin, I can get the default Eclipse shortcuts using command to work as expected when using Emacs+ keybindings.
But in the actual emacs editor, I also use the command key as meta, and want the same behavior in Eclipse. 

There are just a small set of original/default Eclipse shortcuts that I like, and would like to keep, like, for example, the Format code, save, Quick Access. 
Any suggestions on how to get these shortcuts to work with Emacs+ keybindings. 

Thanks, 
Marcel,

**Comment by mfeber** [comment]
After a long absence, I am back in the saddle.  I'm sure you've worked around this issue by now but...
In general, I don't really recommend re-binding useful commands (e.g. CMD+S is search-in-project, which is extremely useful) as it often requires recursive rebinding of the command overridden.  That said, you need to unbind any command that conflicts with your rebinding (e.g. you would need to unbind search-in-project from CMD+S in addition to binding Save to CMD+S).  You also need to pay attention to the context in which the keys are bound.  Another wrinkle is that it is not always easy to tell exactly which (internal) command is associated with the command name that appears in the Keys preference page.  A useful way of determining this is to export all the keys into a .CSV file, which can be checked to make sure that the command you think you are binding is really the command you want to bind.
Anyway, sorry for the atrocious delay.
   Mark
