### ISSUE TITLE
Has Emacs+ become abandonware?

### ISSUE THREAD

**Issue by davidmichaelkarr** [MulgaSoft/e4macs#24]
I noticed that the Emacs+ update site is gone, and the email address Mark used to answer also appears to be gone.  Anyone know anything about this?

**Comment by bjornfor** [comment]
Does anyone have a backup of these files (and willing to share them)?

http://www.mulgasoft.com/emacsplus/e4/update-site/plugins/com.mulgasoft.emacsplus_4.2.0.jar
http://www.mulgasoft.com/emacsplus/e4/update-site/features/com.mulgasoft.emacsplus.feature_4.2.0.jar

**Comment by manandbytes** [comment]
> Does anyone have a backup of these files (and willing to share them)?
What about building it by yourself with pull #21? Not sure if it still works however.

**Comment by davidmichaelkarr** [comment]
Well, I forked the repository and tried to build it.  I did find one
compile error, which I filed an issue for. I was able to fix the compile
error and get the jars to build. I haven't tried to install them in a new
installation yet for testing.

**Comment by moilejter** [comment]
On the Google group, the author mentioned he's not supporting this any more, but will resume the web site as soon as the paperwork goes through.

**Comment by mfeber** [comment]
The "official" eclipse marketplace Emacs+ Install now points to a re-maintained (if somewhat obscure) update site.  Expect the occasional update.
