### ISSUE TITLE
KeyHandlerMinibuffer.checkKey gets compile error on "KeySequence.getInstance(keys)"

### ISSUE THREAD

**Issue by davidmichaelkarr** [MulgaSoft/e4macs#25]
So I had an RCP Eclipse Photon installation.  I cloned e4macs and tried to follow the build instructions.  I immediately saw that the following line in KeyHandlerMinibuffer.checkKey is getting a compile error:

		trigger = KeySequence.getInstance(keys);

keys is a List<Trigger>.  I see that in the version of KeySequence that I see, there is a "getInstance" method that takes a KeyStroke[], and KeyStroke extends Trigger, so it appears that this simply requires doing this:

		trigger = KeySequence.getInstance(keys.toArray(new KeyStroke[0]));

I don't know anything about the version changes that would have occurred since this was last built, or whether fixing this compile error will really fix anything. At least this change fixes the compile error.

**Comment by mfeber** [comment]
This resulted from an eclipse internal cleanup effort for the Oxygen (4.7) release. Fixed in master 4.3.0.
