### ISSUE TITLE
split-window commands no longer work in 2019-09

### ISSUE THREAD

**Issue by davidmichaelkarr** [MulgaSoft/e4macs#27]
I know this isn't being maintained anymore, but I guess I'll log this, in case Mark gets inspired again, or someone capable takes this over.

After upgrading from 2019-06 to 2019-09 today, I'm finding that "split-window-{vertically,horizontally}" now do nothing. There's nothing in the log.  They just don't do anything.  The more primitive "Toggle Split Editor" commands do work, but as described, those are only toggles, so you can only split the window once.

I do have the code loaded into a project in an RCP instance, so I suppose I could step through it if I knew what to look for, but I sure don't.

**Comment by davidmichaelkarr** [comment]
I'm not sure exactly what the problem was, but when I finally set up to debug this, I wasn't able to repeat it in the debug instance.  I still couldn't get it to work when I installed the plugin using a local update site, but when I incremented the version and reinstalled it, it started working again.

**Comment by mfeber** [comment]
I am not seeing this issue, and it sounds like you are no longer seeing it either.

**Comment by davidmichaelkarr** [comment]
That very well could be because I stopped using the version from the update site because of the problems it was having.  As I described in my last note, I got it to work by building it locally and incrementing the version.
