### ISSUE TITLE
As of platform 4.13, need manual import of "javax.inject"

### ISSUE THREAD

**Issue by davidmichaelkarr** [MulgaSoft/e4macs#28]
As of platform 4.13, according to https://www.eclipse.org/eclipse/news/4.13/platform_isv.php#javax-injext (yes, the anchor name is misspelled, but that's it), the javax.inject package is now not automatically exported, so the classes that import classes in that package (Inject class) are getting compile errors.  The fix is to add the following to the MANIFEST.MF file:

    Import-Package: javax.inject;version="1.0.0"

I fixed this in my fork: https://github.com/davidmichaelkarr/e4macs .

**Comment by mfeber** [comment]
As part of the revivification, this import was added.
