### ISSUE TITLE
Cursor movement away from MARK does not select

### ISSUE THREAD

**Issue by paepcke** [MulgaSoft/e4macs#29]
- OS info macOS Mojave (10.14.5)

- Eclipse version and package:
       Eclipse IDE for JavaScript and Web Developers

       Version: 2019-12 (4.14.0)
       Build id: 20191212-1212

java -version
       java version "1.8.0_65"
       Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
       Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

Editor: Python pydev

- Description.
Moving cursor away from just-set mark does not highlight the evolving
region. I.e. does not select. For example:

     cmd-space   [set-mark]
     cmd-p       [previous-line]
     
Should highlight from mark to new point. Note that a region *is* being
defined. For example, cnt-x cnt-x [swap-mark] will toggle between
point and mark.

Also selecting is important, b/c other functions seem to depend on
it.
              
    Example1: <tab> will indent a selected (highlighted) region to the right. 
                     But if that region has no highlight, only the line at point
                    is indented.
              
    Example2: comment-region comments a highlighted region, but not a
              plain old region.
              
    Example3: copy-to-register refuses to offer entry of a register
              name (letter), and instead complains about "No text
              selected"

**Comment by mfeber** [comment]
User had mistakenly re-bound the ancient eclipse set-mark binding, and not the new, improved set-mark-command.
