### ISSUE TITLE
Set-mark  cnt-e Does not Select

### ISSUE THREAD

**Issue by paepcke** [MulgaSoft/e4macs#30]
Small remnant from the otherwise resolved issue of cursor movements not highlighting (i.e. OS-selecting) text. For all but the following your advice about which emacs command to use was the fix.

When moving cursor from mark to end of line (set-mark--->cnt-e) no selection of mark--point occurs. In gnu emacs that selection is made. 

Andreas

**Comment by mfeber** [comment]
This sounds like a riff on the same song.  Make sure the command you have bound is the Emacs+ **end-line** and not the tragically named Eclipse command **line-end**.
See [Issue 23](https://github.com/MulgaSoft/e4macs/issues/23) for hints on how to suss out these sorts of issues.
