### ISSUE TITLE
Lots of things are broken in 2020-09 (4.17.0) release

### ISSUE THREAD

**Issue by FeralWhippet** [MulgaSoft/e4macs#33]
many different commands simply don't work, the "Emacs+ Scheme" option does not show up in the keys scheme popup, etc...

is this project still maintained?

**Comment by mfeber** [comment]
I have not encountered ANY issues with 2020-09, so the chances are it is some issue with your environment.  When submitting a bug, please follow the advice given in the Emacs+ discussion: "If you believe you have found a bug, please file a bug report in the github repository- be sure to include the Eclipse version, your OS type and version, as well as any additional information that might prove useful. Please review the discussions below as well as the documentation and FAQ before submitting a bug."
The discussion list can be found at: http://groups.google.com/group/emacsplus/topics.
